name: HetMan
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - attrs=18.2.0
  - automat=0.7.0
  - backcall=0.1.0
  - binutils_impl_linux-64=2.31.1
  - binutils_linux-64=2.31.1
  - bleach=2.1.4
  - cffi=1.11.5
  - constantly=15.1.0
  - cryptography=2.3.1
  - cycler=0.10.0
  - cython=0.28.5
  - dbus=1.13.2
  - decorator=4.3.0
  - entrypoints=0.2.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - git=2.19.1
  - glib=2.56.2
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - html5lib=1.0.1
  - hyperlink=18.0.0
  - icu=58.2
  - idna=2.7
  - incremental=17.5.0
  - ipykernel=4.10.0
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.1
  - jedi=0.12.1
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libcurl=7.61.1
  - libpng=1.6.35
  - libsodium=1.0.16
  - libssh2=1.8.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.8
  - markupsafe=1.0
  - matplotlib=2.2.3
  - mistune=0.8.3
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - notebook=5.6.0
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.1
  - patsy=0.5.0
  - pcre=8.42
  - perl=5.26.2
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - prometheus_client=0.3.1
  - prompt_toolkit=1.0.15
  - ptyprocess=0.6.0
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.2
  - pycparser=2.19
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pyparsing=2.2.1
  - pyqt=5.9.2
  - pystan=2.18.0.0
  - pyzmq=17.1.2
  - qt=5.9.6
  - qtconsole=4.4.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - service_identity=17.0.0
  - simplegeneric=0.8.1
  - sip=4.19.12
  - statsmodels=0.9.0
  - terminado=0.8.1
  - testpath=0.3.1
  - tornado=5.1.1
  - traitlets=4.3.2
  - twisted=18.7.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - widgetsnbextension=3.4.1
  - zeromq=4.2.5
  - zope=1.0
  - zope.interface=4.5.0
  - filechunkio=1.6
  - ftputil=3.2
  - pygraphviz=1.3.1
  - pysftp=0.2.9
  - rsa=3.1.4
  - snakemake=5.4.3
  - snakemake-minimal=5.4.3
  - urllib3=1.12
  - aioeasywebdav=2.2.0
  - aiohttp=3.4.4
  - async-timeout=3.0.1
  - boto3=1.7.84
  - botocore=1.10.84
  - ca-certificates=2019.3.9
  - cachetools=2.1.0
  - certifi=2018.8.24
  - chardet=3.0.4
  - configargparse=0.13.0
  - docutils=0.14
  - dropbox=7.3.1
  - fribidi=1.0.5
  - gitdb2=2.0.5
  - gitpython=2.1.11
  - google-auth=1.6.3
  - google-auth-httplib2=0.0.3
  - google-cloud-core=0.24.1
  - google-cloud-storage=1.1.1
  - google-resumable-media=0.0.2
  - googleapis-common-protos=1.5.8
  - graphite2=1.3.13
  - harfbuzz=1.9.0
  - httplib2=0.11.3
  - idna_ssl=1.0.0
  - jmespath=0.9.4
  - libprotobuf=3.6.0
  - libtiff=4.0.9
  - llvmlite=0.25.0
  - matplotlib-venn=0.11.5
  - multidict=4.4.2
  - networkx=2.2
  - numba=0.40.0
  - openssl=1.0.2r
  - paramiko=2.4.1
  - pixman=0.34.0
  - prettytable=0.7.2
  - protobuf=3.6.0
  - psutil=5.4.7
  - pynacl=1.1.2
  - python-irodsclient=0.7.0
  - pyyaml=3.13
  - ratelimiter=1.2.0
  - requests=2.13.0
  - s3transfer=0.1.13
  - smmap2=2.0.5
  - umap-learn=0.3.2
  - wrapt=1.10.11
  - xmlrunner=1.7.7
  - yaml=0.1.7
  - yarl=1.2.6
  - bcrypt=3.1.4
  - blas=1.0
  - cairo=1.14.12
  - datrie=0.7.1
  - dill=0.2.8.2
  - graphviz=2.40.1
  - intel-openmp=2019.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=8.2.0
  - mkl=2018.0.3
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - ncurses=6.1
  - numpy=1.14.6
  - numpy-base=1.14.6
  - pandas=0.23.4
  - pango=1.42.4
  - pip=10.0.1
  - python=3.5.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - readline=7.0
  - scikit-learn=0.19.2
  - scipy=1.1.0
  - setuptools=40.2.0
  - six=1.11.0
  - sqlite=3.26.0
  - tk=8.6.8
  - wheel=0.31.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - aql==0.0.0
    - asciimatics==1.10.0
    - backports.csv==1.0.6
    - circlify==0.9.1
    - colorama==0.4.1
    - configobj==5.0.6
    - configparser==3.7.3
    - contextlib2==0.5.5
    - deprecation==2.0.5
    - distro==1.4.0
    - dryad==0.3.2b0
    - dvc==0.32.1
    - future==0.17.1
    - grandalf==0.6
    - jsonpath-rw==1.4.0
    - keyring==12.0.2
    - keyrings.alt==3.1.1
    - line-profiler==2.1.2
    - nanotime==0.5.2
    - packaging==18.0
    - pillow==5.4.1
    - ply==3.11
    - pyfiglet==0.8.post1
    - schema==0.7.0
    - secretstorage==2.3.1
    - synapseclient==1.9.0
    - zc.lockfile==1.4

