name: HetMan
channels:
  - bioconda
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - aioeasywebdav=2.4.0
  - aiohttp=3.5.4
  - appdirs=1.4.3
  - asciimatics=1.11.0
  - asn1crypto=0.24.0
  - async-timeout=3.0.1
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - backcall=0.1.0
  - backports=1.0
  - bcrypt=3.1.6
  - binutils_impl_linux-64=2.31.1
  - binutils_linux-64=2.31.1
  - blas=1.0
  - bleach=3.1.0
  - boto3=1.9.199
  - botocore=1.12.199
  - bzip2=1.0.8
  - ca-certificates=2019.8.28
  - cachetools=2.1.0
  - cairo=1.16.0
  - certifi=2019.9.11
  - cffi=1.12.3
  - chardet=3.0.4
  - cmarkgfm=0.4.2
  - colorama=0.4.1
  - configargparse=0.14.0
  - configobj=5.0.6
  - configparser=3.7.4
  - contextlib2=0.5.5
  - cryptography=2.7
  - cycler=0.10.0
  - cython=0.29.13
  - datrie=0.7.1
  - dbus=1.13.6
  - decorator=4.4.0
  - dill=0.3.0
  - distro=1.4.0
  - docutils=0.14
  - dropbox=9.4.0
  - dvc=0.54.1
  - expat=2.2.6
  - fftw=3.3.8
  - filechunkio=1.6
  - fontconfig=2.13.1
  - freetype=2.9.1
  - fribidi=1.0.5
  - ftputil=3.2
  - funcy=1.13
  - future=0.17.1
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gdk-pixbuf=2.36.12
  - gettext=0.19.8.1
  - ghostscript=9.18
  - giflib=5.1.7
  - git=2.20.1
  - gitdb2=2.0.5
  - gitpython=2.1.13
  - glib=2.58.3
  - gobject-introspection=1.58.2
  - google-auth=1.0.1
  - google-auth-httplib2=0.0.3
  - google-cloud-core=0.24.1
  - google-cloud-storage=1.1.1
  - google-resumable-media=0.0.2
  - googleapis-common-protos=1.6.0
  - grandalf=0.6
  - graphite2=1.3.13
  - graphviz=2.40.1
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=2.4.0
  - httplib2=0.13.1
  - humanize=0.5.1
  - icu=58.2
  - idna=2.8
  - idna_ssl=1.1.0
  - imagemagick=7.0.8_63
  - importlib_metadata=0.19
  - inflect=2.1.0
  - intel-openmp=2019.4
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jedi=0.15.1
  - jinja2=2.10.1
  - jmespath=0.9.4
  - joblib=0.13.2
  - jpeg=9c
  - jsonpath-ng=1.4.3
  - jsonschema=3.0.2
  - kiwisolver=1.1.0
  - krb5=1.16.1
  - libcroco=0.6.13
  - libcurl=7.65.3
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc=7.2.0
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - libpng=1.6.37
  - libprotobuf=3.8.0
  - librsvg=2.44.15
  - libsodium=1.0.16
  - libssh2=1.8.2
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp=1.0.1
  - libxcb=1.13
  - libxml2=2.9.9
  - llvmlite=0.29.0
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.14
  - mkl_random=1.0.2
  - more-itertools=7.2.0
  - multidict=4.5.2
  - nanotime=0.5.2
  - ncurses=6.1
  - networkx=2.3
  - numba=0.45.1
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1
  - packaging=19.1
  - pandas=0.25.1
  - pango=1.42.4
  - paramiko=2.4.2
  - parso=0.5.1
  - pathspec=0.5.9
  - patsy=0.5.1
  - pcre=8.43
  - perl=5.26.2
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.1.0
  - pip=19.2.2
  - pixman=0.38.0
  - pkg-config=0.29.2
  - pkginfo=1.5.0.1
  - pluggy=0.12.0
  - ply=3.11
  - prettytable=0.7.2
  - prompt_toolkit=2.0.9
  - protobuf=3.8.0
  - psutil=5.6.3
  - ptyprocess=0.6.0
  - py=1.8.0
  - pyasn1=0.4.6
  - pyasn1-modules=0.0.5
  - pycparser=2.19
  - pyfiglet=0.8.post1
  - pygments=2.4.2
  - pygraphviz=1.3.1
  - pynacl=1.3.0
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - pysftp=0.2.9
  - pysocks=1.7.0
  - pystan=2.19.0.0
  - pytest=5.0.1
  - python=3.6.9
  - python-dateutil=2.8.0
  - python-irodsclient=0.7.0
  - pytz=2019.2
  - pyyaml=5.1.2
  - qt=5.9.7
  - ratelimiter=1.2.0
  - readline=7.0
  - readme_renderer=24.0
  - requests=2.22.0
  - requests-toolbelt=0.9.1
  - rsa=3.1.4
  - ruamel=1.0
  - ruamel.yaml=0.15.100
  - s3transfer=0.2.1
  - schema=0.7.0
  - scikit-learn=0.21.2
  - scipy=1.3.1
  - seaborn=0.9.0
  - setuptools=41.0.1
  - shortuuid=0.5.0
  - sip=4.19.13
  - six=1.12.0
  - smmap2=2.0.5
  - snakemake=5.5.4
  - snakemake-minimal=5.5.4
  - sqlite=3.29.0
  - statsmodels=0.10.1
  - tbb=2019.4
  - tk=8.6.8
  - tornado=6.0.3
  - tqdm=4.32.1
  - traitlets=4.3.2
  - treelib=1.5.5
  - twine=1.13.0
  - umap-learn=0.3.10
  - urllib3=1.24.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - wrapt=1.11.2
  - xlrd=1.2.0
  - xmlrunner=1.7.7
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.8
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.12
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - yarl=1.3.0
  - zc.lockfile=1.4
  - zipp=0.5.2
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - backports-csv==1.0.7
    - deprecated==1.2.4
    - dryad==0.4.1b0
    - entrypoints==0.3
    - keyring==12.0.2
    - keyrings-alt==3.1
    - secretstorage==2.3.1
    - synapseclient==1.9.3

