name: HetMan
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - attrs=18.2.0
  - automat=0.7.0
  - backcall=0.1.0
  - binutils_impl_linux-64=2.31.1
  - binutils_linux-64=2.31.1
  - bleach=2.1.4
  - ca-certificates=2018.03.07
  - certifi=2018.8.24
  - cffi=1.11.5
  - constantly=15.1.0
  - cryptography=2.3.1
  - cycler=0.10.0
  - cython=0.28.5
  - dbus=1.13.2
  - decorator=4.3.0
  - entrypoints=0.2.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - git=2.19.1
  - glib=2.56.2
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - html5lib=1.0.1
  - hyperlink=18.0.0
  - icu=58.2
  - idna=2.7
  - incremental=17.5.0
  - ipykernel=4.10.0
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.1
  - jedi=0.12.1
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libcurl=7.61.1
  - libpng=1.6.35
  - libsodium=1.0.16
  - libssh2=1.8.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.8
  - markupsafe=1.0
  - matplotlib=2.2.3
  - mistune=0.8.3
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - notebook=5.6.0
  - openssl=1.0.2p
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.1
  - patsy=0.5.0
  - pcre=8.42
  - perl=5.26.2
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - prometheus_client=0.3.1
  - prompt_toolkit=1.0.15
  - ptyprocess=0.6.0
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.2
  - pycparser=2.19
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pyparsing=2.2.1
  - pyqt=5.9.2
  - pystan=2.18.0.0
  - pyzmq=17.1.2
  - qt=5.9.6
  - qtconsole=4.4.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - service_identity=17.0.0
  - simplegeneric=0.8.1
  - sip=4.19.12
  - statsmodels=0.9.0
  - terminado=0.8.1
  - testpath=0.3.1
  - tornado=5.1.1
  - traitlets=4.3.2
  - twisted=18.7.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - widgetsnbextension=3.4.1
  - zeromq=4.2.5
  - zope=1.0
  - zope.interface=4.5.0
  - llvmlite=0.25.0
  - matplotlib-venn=0.11.5
  - numba=0.40.0
  - umap-learn=0.3.2
  - blas=1.0
  - dill=0.2.8.2
  - intel-openmp=2019.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=8.2.0
  - mkl=2018.0.3
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - ncurses=6.1
  - numpy=1.14.6
  - numpy-base=1.14.6
  - pandas=0.23.4
  - pip=10.0.1
  - python=3.5.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - readline=7.0
  - scikit-learn=0.19.2
  - scipy=1.1.0
  - setuptools=40.2.0
  - six=1.11.0
  - sqlite=3.26.0
  - tk=8.6.8
  - wheel=0.31.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - aql==0.0.0
    - backports.csv==1.0.6
    - chardet==3.0.4
    - deprecation==2.0.5
    - dryad==0.3.2a9
    - future==0.17.1
    - keyring==12.0.2
    - keyrings.alt==3.1.1
    - packaging==18.0
    - requests==2.21.0
    - secretstorage==2.3.1
    - synapseclient==1.9.0
    - urllib3==1.24.1

