name: research
channels:
  - bioconda
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aioeasywebdav=2.4.0
  - aiohttp=3.6.2
  - appdirs=1.4.4
  - asciimatics=1.11.0
  - async-timeout=3.0.1
  - attrs=20.1.0
  - backcall=0.2.0
  - bcrypt=3.2.0
  - binutils_impl_linux-64=2.31.1
  - binutils_linux-64=2.31.1
  - biopython=1.77
  - blas=2.17
  - bleach=3.2.1
  - boto3=1.9.66
  - botocore=1.12.67
  - bzip2=1.0.8
  - ca-certificates=2020.7.22
  - cachetools=4.1.1
  - cairo=1.14.12
  - certifi=2020.6.20
  - cffi=1.14.2
  - chardet=3.0.4
  - clustalw=2.1
  - cmarkgfm=0.4.2
  - colorama=0.4.3
  - configargparse=1.2.3
  - configobj=5.0.6
  - configparser=5.0.0
  - contextlib2=0.6.0.post1
  - cryptography=3.1.1
  - curl=7.71.1
  - cycler=0.10.0
  - cython=0.29.21
  - datrie=0.8.2
  - dbus=1.13.12
  - decorator=4.4.2
  - dill=0.3.2
  - distro=1.5.0
  - docutils=0.16
  - dropbox=10.2.0
  - dvc=0.54.1
  - ensembl-vep=99.2
  - expat=2.2.9
  - filechunkio=1.6
  - fontconfig=2.13.1
  - freetype=2.10.2
  - ftputil=3.2
  - funcy=1.14
  - future=0.18.2
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gettext=0.19.8.1
  - giflib=5.1.4
  - git=2.23.0
  - gitdb=4.0.5
  - gitpython=3.1.3
  - glib=2.56.2
  - google-api-core=1.17.0
  - google-auth=1.21.0
  - google-cloud-core=1.4.1
  - google-cloud-storage=1.28.1
  - google-resumable-media=0.5.1
  - googleapis-common-protos=1.51.0
  - grandalf=0.6
  - graphite2=1.3.14
  - graphviz=2.38.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=1.8.8
  - htslib=1.9
  - humanize=0.5.1
  - icu=58.2
  - idna=2.10
  - idna_ssl=1.1.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - inflect=4.1.0
  - iniconfig=1.0.1
  - ipdb=0.13.3
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - jinja2=2.11.2
  - jmespath=0.10.0
  - joblib=0.16.0
  - jpeg=9d
  - jsonpath-ng=1.5.2
  - jsonschema=3.2.0
  - kiwisolver=1.2.0
  - krb5=1.18.2
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libdb=6.1.26
  - libdeflate=1.2
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc=7.2.0
  - libgcc-ng=9.1.0
  - libgd=2.2.5
  - libgfortran-ng=7.3.0
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libprotobuf=3.13.0
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp=1.0.1
  - libxcb=1.14
  - libxml2=2.9.10
  - libxslt=1.1.34
  - llvm-openmp=10.0.1
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - more-itertools=8.5.0
  - multidict=4.7.3
  - mysql-connector-c=6.1.6
  - nanotime=0.5.2
  - ncurses=6.2
  - networkx=2.5
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openssl=1.1.1h
  - packaging=20.4
  - paml=4.9
  - pandas=1.1.1
  - pango=1.40.14
  - paramiko=2.7.2
  - parso=0.7.0
  - pathspec=0.7.0
  - patsy=0.5.1
  - pcre=8.44
  - perl=5.26.2
  - perl-aceperl=1.92
  - perl-algorithm-diff=1.1903
  - perl-algorithm-munkres=0.08
  - perl-apache-test=1.40
  - perl-app-cpanminus=1.7044
  - perl-appconfig=1.71
  - perl-array-compare=3.0.1
  - perl-autoloader=5.74
  - perl-base=2.23
  - perl-bio-asn1-entrezgene=1.73
  - perl-bio-coordinate=1.007001
  - perl-bio-db-hts=3.01
  - perl-bio-featureio=1.6.905
  - perl-bio-phylo=0.58
  - perl-bio-samtools=1.43
  - perl-bio-tools-phylo-paml=1.7.3
  - perl-bio-tools-run-alignment-clustalw=1.7.4
  - perl-bio-tools-run-alignment-tcoffee=1.7.4
  - perl-bioperl=1.7.2
  - perl-bioperl-core=1.007002
  - perl-bioperl-run=1.007002
  - perl-business-isbn=3.004
  - perl-business-isbn-data=20140910.003
  - perl-cache-cache=1.08
  - perl-capture-tiny=0.48
  - perl-carp=1.38
  - perl-cgi=4.44
  - perl-class-data-inheritable=0.08
  - perl-class-inspector=1.34
  - perl-class-load=0.25
  - perl-class-load-xs=0.10
  - perl-class-method-modifiers=2.12
  - perl-clone=0.42
  - perl-common-sense=3.74
  - perl-compress-raw-bzip2=2.087
  - perl-compress-raw-zlib=2.087
  - perl-constant=1.33
  - perl-convert-binary-c=0.78
  - perl-convert-binhex=1.125
  - perl-crypt-rc4=2.02
  - perl-data-dumper=2.173
  - perl-data-optlist=0.110
  - perl-data-stag=0.14
  - perl-date-format=2.30
  - perl-db-file=1.852
  - perl-dbd-mysql=4.046
  - perl-dbd-sqlite=1.64
  - perl-dbi=1.642
  - perl-devel-globaldestruction=0.14
  - perl-devel-overloadinfo=0.005
  - perl-devel-stacktrace=2.04
  - perl-digest-hmac=1.03
  - perl-digest-md5=2.55
  - perl-digest-perl-md5=1.9
  - perl-digest-sha1=2.13
  - perl-dist-checkconflicts=0.11
  - perl-dynaloader=1.25
  - perl-email-date-format=1.005
  - perl-encode=2.88
  - perl-encode-locale=1.05
  - perl-error=0.17027
  - perl-eval-closure=0.14
  - perl-exception-class=1.44
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002001
  - perl-extutils-makemaker=7.36
  - perl-file-listing=6.04
  - perl-file-path=2.16
  - perl-file-slurp-tiny=0.004
  - perl-file-sort=1.01
  - perl-file-temp=0.2304
  - perl-file-which=1.23
  - perl-font-afm=1.20
  - perl-font-ttf=1.06
  - perl-gd=2.71
  - perl-getopt-long=2.50
  - perl-graph=0.9704
  - perl-graphviz=2.24
  - perl-html-element-extended=1.18
  - perl-html-entities-numbered=0.04
  - perl-html-formatter=2.16
  - perl-html-parser=3.72
  - perl-html-tableextract=2.13
  - perl-html-tagset=3.20
  - perl-html-tidy=1.60
  - perl-html-tree=5.07
  - perl-html-treebuilder-xpath=0.14
  - perl-http-cookies=6.04
  - perl-http-daemon=6.01
  - perl-http-date=6.02
  - perl-http-message=6.18
  - perl-http-negotiate=6.01
  - perl-image-info=1.38
  - perl-image-size=3.300
  - perl-io-compress=2.087
  - perl-io-html=1.001
  - perl-io-sessiondata=1.03
  - perl-io-socket-ssl=2.066
  - perl-io-string=1.08
  - perl-io-stringy=2.111
  - perl-io-tty=1.12
  - perl-ipc-run=20180523.0
  - perl-ipc-sharelite=0.17
  - perl-jcode=2.07
  - perl-json=4.02
  - perl-json-xs=2.34
  - perl-lib=0.63
  - perl-libwww-perl=6.39
  - perl-libxml-perl=0.08
  - perl-list-moreutils=0.428
  - perl-list-moreutils-xs=0.428
  - perl-lwp-mediatypes=6.04
  - perl-lwp-protocol-https=6.07
  - perl-lwp-simple=6.15
  - perl-mailtools=2.21
  - perl-math-cdf=0.1
  - perl-math-derivative=1.01
  - perl-math-random=0.72
  - perl-math-spline=0.02
  - perl-mime-base64=3.15
  - perl-mime-lite=3.030
  - perl-mime-tools=5.508
  - perl-mime-types=2.17
  - perl-mldbm=2.05
  - perl-module-implementation=0.09
  - perl-module-runtime=0.016
  - perl-module-runtime-conflicts=0.003
  - perl-moo=2.003004
  - perl-moose=2.2011
  - perl-mozilla-ca=20180117
  - perl-mro-compat=0.13
  - perl-net-http=6.19
  - perl-net-ssleay=1.88
  - perl-ntlm=1.09
  - perl-ole-storage_lite=0.19
  - perl-package-deprecationmanager=0.17
  - perl-package-stash=0.38
  - perl-package-stash-xs=0.28
  - perl-params-util=1.07
  - perl-parent=0.236
  - perl-parse-recdescent=1.967015
  - perl-pathtools=3.75
  - perl-pdf-api2=2.035
  - perl-perlio-gzip=0.20
  - perl-pod-escapes=1.07
  - perl-pod-usage=1.69
  - perl-postscript=0.06
  - perl-role-tiny=2.000008
  - perl-scalar-list-utils=1.52
  - perl-sereal=4.007
  - perl-sereal-decoder=4.007
  - perl-sereal-encoder=4.007
  - perl-set-intervaltree=0.12
  - perl-set-scalar=1.29
  - perl-soap-lite=1.19
  - perl-socket=2.027
  - perl-sort-naturally=1.03
  - perl-spreadsheet-parseexcel=0.65
  - perl-spreadsheet-writeexcel=2.40
  - perl-statistics-descriptive=3.0702
  - perl-storable=3.15
  - perl-sub-exporter=0.987
  - perl-sub-exporter-progressive=0.001013
  - perl-sub-identify=0.14
  - perl-sub-install=0.928
  - perl-sub-name=0.21
  - perl-sub-quote=2.006003
  - perl-sub-uplevel=0.2800
  - perl-svg=2.84
  - perl-svg-graph=0.02
  - perl-task-weaken=1.06
  - perl-template-toolkit=2.26
  - perl-test=1.26
  - perl-test-deep=1.128
  - perl-test-differences=0.67
  - perl-test-exception=0.43
  - perl-test-harness=3.42
  - perl-test-leaktrace=0.16
  - perl-test-most=0.35
  - perl-test-requiresinternet=0.05
  - perl-test-warn=0.36
  - perl-text-csv=2.00
  - perl-text-diff=1.45
  - perl-tie-ixhash=1.23
  - perl-time-hires=1.9760
  - perl-time-local=1.28
  - perl-timedate=2.30
  - perl-tree-dag_node=1.31
  - perl-try-tiny=0.30
  - perl-type-tiny=1.004004
  - perl-types-serialiser=1.0
  - perl-unicode-map=0.112
  - perl-uri=1.76
  - perl-www-robotrules=6.02
  - perl-xml-dom=1.46
  - perl-xml-dom-xpath=0.14
  - perl-xml-filter-buffertext=1.01
  - perl-xml-libxml=2.0132
  - perl-xml-libxslt=1.94
  - perl-xml-namespacesupport=1.12
  - perl-xml-parser=2.44
  - perl-xml-regexp=0.04
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - perl-xml-sax-expat=0.51
  - perl-xml-sax-writer=0.57
  - perl-xml-simple=2.25
  - perl-xml-twig=3.52
  - perl-xml-writer=0.625
  - perl-xml-xpath=1.44
  - perl-xml-xpathengine=0.14
  - perl-xsloader=0.24
  - perl-yaml=1.29
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.2
  - pixman=0.40.0
  - pkginfo=1.5.0.1
  - pluggy=0.13.1
  - ply=3.11
  - prettytable=0.7.2
  - prompt-toolkit=3.0.7
  - protobuf=3.13.0
  - psutil=5.7.2
  - ptyprocess=0.6.0
  - py=1.9.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyfiglet=0.8.post1
  - pygments=2.6.1
  - pygraphviz=1.3.1
  - pynacl=1.4.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pystan=2.19.0.0
  - pytest=6.0.2
  - python=3.6.10
  - python-dateutil=2.8.1
  - python-irodsclient=0.8.2
  - python_abi=3.6
  - pytz=2020.1
  - pyyaml=5.3.1
  - qt=5.9.7
  - ratelimiter=1.2.0
  - readline=8.0
  - readme_renderer=24.0
  - requests=2.24.0
  - requests-toolbelt=0.9.1
  - rsa=3.1.4
  - ruamel=1.0
  - ruamel.yaml=0.15.100
  - s3transfer=0.1.13
  - schema=0.7.0
  - scikit-learn=0.21.3
  - scipy=1.5.2
  - seaborn=0.10.1
  - setuptools=49.6.0
  - shortuuid=1.0.1
  - sip=4.19.24
  - six=1.15.0
  - smmap=3.0.4
  - snakemake=5.3.0
  - snakemake-minimal=5.3.0
  - sqlite=3.33.0
  - statsmodels=0.11.1
  - t_coffee=11.0.8
  - tidyp=1.04
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.0.4
  - tqdm=4.50.2
  - traitlets=4.3.3
  - treelib=1.6.1
  - twine=2.0.0
  - typing_extensions=3.7.4.3
  - unzip=6.0
  - urllib3=1.24.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - wrapt=1.12.1
  - xlrd=1.2.0
  - xmlrunner=1.7.7
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.5.1
  - zc.lockfile=2.0
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - deprecated==1.2.10
    - dryads==0.5.0a2
    - entrypoints==0.3
    - keyring==12.0.2
    - keyrings-alt==3.1
    - secretstorage==2.3.1
    - synapseclient==2.2.0
